esphome:
  name: can-logger

external_components:
  - source: "github://asergunov/esphome_sd_card@file-server"
  - source: "github://asergunov/esphome_esphome@tx_mode"
    components:
    # to let logger subscribe to TX events
      - canbus
      - esp32_can
  - source: "github://asergunov/esphome_esphome@esp32-configuration"
    # to workaround idf version selection
      - esp32
  - source: "github://asergunov/esphome-can-sniffer"
    components:
      - can_logger

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.4.1 # multiple can interfaces support since 5.2
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

time:
  platform: sntp

packages:
  sdcard: !include sdcard.yaml
  # the way to not duplicate code
  can1: !include
    file: canbus.yaml
    vars:
      canbus_id: can1
      canbus_name: CAN1
      can_id: 100
      rx_pin: GPIO4
      tx_pin: GPIO16
      bit_rate: 500KBPS
  can2: !include
    file: canbus.yaml
    vars:
      canbus_id: can2
      canbus_name: CAN2
      can_id: 200
      rx_pin: GPIO5
      tx_pin: GPIO17
      bit_rate: 500KBPS

can_logger:
  - file: 
      path: "/can.log"
      format: crtd
    can:
      - canbus_id: can1
        log_id: 1
      - canbus_id: can2
        log_id: 2

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  # level: VERY_VERBOSE
  logs: 
    wifi: DEBUG

api:
  encryption: 
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:
    ssid: "Can-Logger Fallback Hotspot"
    password: !secret ap_password

captive_portal:

switch:
  - platform: gpio
    pin: GPIO9
    name: Transceivers sleep
  - platform: gpio
    pin: GPIO14
    name: External Antenna