
spi:
  - mosi_pin: GPIO2
    miso_pin: GPIO7
    clk_pin: GPIO6

sd_mmc_card:
  id: sd_card
  type: sd_spi
  mode_1bit: true
  data3_pin: GPIO21
  # data_rate: 20MHz

sd_file_server:
  id: file_server
  url_prefix: file
  root_path: "/"
  enable_deletion: true
  enable_download: true
  enable_upload: true
sensor:
  - platform: sd_mmc_card
    type: used_space
    name: "SD card used space"
  - platform: sd_mmc_card
    type: total_space
    name: "SD card total space"
  - platform: sd_mmc_card
    type: free_space
    name: "SD card free space"
  - platform: sd_mmc_card
    type: max_frequency
    name: "SD card Max Frequency"
  - platform: sd_mmc_card
    type: real_frequency
    name: "SD card Real Frequency"

text_sensor:
  - platform: sd_mmc_card
    sd_card_type:
      name: "SD card type"