esphome:
  name: two-can-logger

external_components:
  - source: "github://asergunov/esphome_sd_card@file-server"
  - source: "../../components"
    components:
      - sdcard_logger
      - uart_dump

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

packages:
  sdcard: !include sdcard.yaml

time:
  platform: sntp


uart:
  - id: lin_uart
    tx_pin: GPIO4 # comment out to disabling transfer
    rx_pin: GPIO5
    baud_rate: 9600
    data_bits: 8
    parity: NONE
    stop_bits: 2

sdcard_logger:
  - file: 
      path: "/can.log"
      format: crtd
    uart:
      - uart_id: lin_uart
        log_id: 1

uart_dump:
    uart_id: lin_uart

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG
  # level: VERY_VERBOSE
  logs: 
    wifi: DEBUG

api:
  encryption: 
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap:
    ssid: "Can-Logger Fallback Hotspot"
    password: !secret ap_password
